name: AfterMerge report

on:
  workflow_dispatch:
    inputs:
      pull-request:
        description: Merged pull-request number
        required: true
        type: number

permissions:
  contents: read
  pull-requests: read

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: PtPetrov/aftermerge@v0.1
        with:
          pull-request: ${{ inputs.pull-request }}
          github-token: ${{ github.token }}
